<?php
return array(
    'shop_seofilter_basic_settings' => array(
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'name',
        ),
    ),
    'shop_seofilter_default_template' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'name' => array('varchar', 75, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'name'),
        ),
    ),
    'shop_seofilter_default_template_settings' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'name' => array('varchar', 75, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'name'),
        ),
    ),
    'shop_seofilter_filter' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'seo_name' => array('text', 'null' => 0),
        'url' => array('varchar', 255, 'null' => 0),
        'is_enabled' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '1'),
        'feature_value_hash' => array('char', 40, 'null' => 0),
        'storefronts_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'categories_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'update_datetime' => array('datetime', 'null' => 0),
        'generator_process_id' => array('varchar', 16),
        'feature_values_count' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0),
        'feature_value_ranges_count' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0),
        'default_product_sort' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'empty_page_http_code' => array('varchar', 5),
        ':keys' => array(
            'PRIMARY' => 'id',
            'is_enabled' => 'is_enabled',
            'url_is_enabled' => array('url', 'is_enabled'),
            'is_enabled_feature_value_hash' => array('feature_value_hash', 'is_enabled'),
            'update_datetime' => 'update_datetime',
            'generator_process_id' => 'generator_process_id',
            'feature_values_count' => 'feature_values_count',
        ),
    ),
    'shop_seofilter_filter_category' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 11, 'null' => 0),
        'category_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id_category_id' => array('filter_id', 'category_id'),
            'filter_id' => 'filter_id',
            'category_id' => 'category_id',
        ),
    ),
    'shop_seofilter_filter_feature_value' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 11, 'null' => 0),
        'feature_id' => array('int', 11, 'null' => 0),
        'value_id' => array('int', 11),
        'sort' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id' => 'filter_id',
            'filter_id_feature_id_value_id' => array('filter_id', 'feature_id', 'value_id'),
        ),
    ),
    'shop_seofilter_filter_feature_value_range' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 11, 'null' => 0),
        'feature_id' => array('int', 11, 'null' => 0),
        'type' => array('varchar', 16, 'null' => 0),
        'begin_base_unit' => array('float'),
        'end_base_unit' => array('float'),
        'unit' => array('varchar', 255, 'null' => 0),
        'begin' => array('float'),
        'end' => array('float'),
        'sort' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id' => 'filter_id',
        ),
    ),
    'shop_seofilter_filter_field' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'sort' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'shop_seofilter_filter_field_value' => array(
        'filter_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'field_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('filter_id', 'field_id'),
        ),
    ),
    'shop_seofilter_filter_personal_canonical' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'is_enabled' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '1'),
        'storefronts_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'categories_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'canonical_url_template' => array('varchar', 2048, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id' => 'filter_id',
            'filter_id_is_enabled' => array('filter_id', 'is_enabled'),
        ),
    ),
    'shop_seofilter_filter_personal_canonical_category' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'canonical_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'canonical_id' => 'canonical_id',
            'category_id' => 'category_id',
            'canonical_id_category_id' => array('canonical_id', 'category_id'),
        ),
    ),
    'shop_seofilter_filter_personal_canonical_storefront' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'canonical_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'storefront' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'canonical_id' => 'canonical_id',
            'storefront' => 'storefront',
            'canonical_id_storefront' => array('canonical_id', 'storefront'),
        ),
    ),
    'shop_seofilter_filter_personal_rule' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 11, 'null' => 0),
        'is_enabled' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '1'),
        'default_product_sort' => array('varchar', 32, 'null' => 0, 'default' => ''),
        'seo_h1' => array('text', 'null' => 0),
        'seo_description' => array('text', 'null' => 0),
        'meta_title' => array('text', 'null' => 0),
        'meta_description' => array('text', 'null' => 0),
        'meta_keywords' => array('text', 'null' => 0),
        'additional_description' => array('text', 'null' => 0),
        'storefronts_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'categories_use_mode' => array('enum', "'ALL','EXCEPT','LISTED'", 'null' => 0, 'default' => 'ALL'),
        'is_pagination_templates_enabled' => array('tinyint', 3, 'unsigned' => 1, 'null' => 0, 'default' => '0'),
        'seo_h1_pagination' => array('text', 'null' => 0),
        'seo_description_pagination' => array('text', 'null' => 0),
        'meta_title_pagination' => array('text', 'null' => 0),
        'meta_description_pagination' => array('text', 'null' => 0),
        'meta_keywords_pagination' => array('text', 'null' => 0),
        'additional_description_pagination' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id_is_enabled' => array('is_enabled', 'filter_id'),
            'is_enabled' => 'is_enabled',
        ),
    ),
    'shop_seofilter_filter_personal_rule_category' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'rule_id' => array('int', 11, 'null' => 0),
        'category_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'rule_id_category_id' => array('rule_id', 'category_id'),
            'rule_id' => 'rule_id',
            'category_id' => 'category_id',
        ),
    ),
    'shop_seofilter_filter_personal_rule_storefront' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'rule_id' => array('int', 11, 'null' => 0),
        'storefront' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'rule_id' => 'rule_id',
            'storefront' => 'storefront',
            'rule_id_storefront' => array('rule_id', 'storefront'),
        ),
    ),
    'shop_seofilter_filter_storefront' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'filter_id' => array('int', 11, 'null' => 0),
        'storefront' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'filter_id' => 'filter_id',
            'storefront' => 'storefront',
            'filter_id_storefront' => array('filter_id', 'storefront'),
        ),
    ),
    'shop_seofilter_filter_tree_category_feature_settings' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'feature_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'enabled_for_storefronts' => array('enum', "'ALL','NONE','LISTED'", 'null' => 0, 'default' => 'ALL'),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'category_id', 'feature_id'),
            'category_id_feature_id' => array('category_id', 'feature_id'),
        ),
    ),
    'shop_seofilter_filter_tree_category_settings' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'enabled_for_storefronts' => array('enum', "'ALL','NONE','LISTED'", 'null' => 0, 'default' => 'ALL'),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'category_id'),
            'category_id' => 'category_id',
        ),
    ),
    'shop_seofilter_generator_history' => array(
        'id' => array('int', 10, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'generator_id' => array('varchar', 16, 'null' => 0),
        'total' => array('int', 10, 'unsigned' => 1),
        'created' => array('int', 10, 'unsigned' => 1),
        'skipped' => array('int', 10, 'unsigned' => 1),
        'date' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'generator_id' => array('generator_id', 'unique' => 1),
            'date' => 'date',
        ),
    ),
    'shop_seofilter_generator_history_feature' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'history_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'feature_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'order' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'history_id' => 'history_id',
        ),
    ),
    'shop_seofilter_generator_history_feature_value' => array(
        'id' => array('int', 11, 'unsigned' => 1, 'null' => 0, 'autoincrement' => 1),
        'generator_history_feature_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        'value_id' => array('int', 11, 'unsigned' => 1, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'generator_history_feature_id' => 'generator_history_feature_id',
        ),
    ),
    'shop_seofilter_productfilters_category_feature_rule' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1),
        'feature_id' => array('int', 10, 'unsigned' => 1),
        'link_category_id' => array('int', 10, 'unsigned' => 1),
        'display_link' => array('enum', "'Y','N'", 'default' => 'Y'),
        ':keys' => array(
            'storefront_category_id_feature_id' => array('storefront', 'category_id', 'feature_id', 'unique' => 1),
        ),
    ),
    'shop_seofilter_productfilters_category_settings' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'category_id', 'name'),
        ),
    ),
    'shop_seofilter_productfilters_settings' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'name'),
        ),
    ),
    'shop_seofilter_sitemap_cache' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'filter_ids' => array('text', 'null' => 0),
        'lastmod' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'category_id'),
        ),
    ),
    'shop_seofilter_sitemap_cache_queue' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'category_id' => array('int', 10, 'unsigned' => 1, 'null' => 0),
        'filter_ids' => array('text', 'null' => 0),
        'filter_ids_with_single_value' => array('text'),
        'refresh_after' => array('int', 11, 'null' => 0),
        'domain' => array('varchar', 255, 'null' => 0),
        'shop_url' => array('varchar', 255, 'null' => 0),
        'lock_timestamp' => array('int', 10, 'unsigned' => 1),
        'cache_generator_id' => array('varchar', 16),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'category_id'),
            'refresh_after_lock_timestamp' => array('refresh_after', 'lock_timestamp'),
            'category_id_lock_timestamp' => array('category_id', 'lock_timestamp'),
            'category_id' => 'category_id',
            'cache_generator_id' => 'cache_generator_id',
        ),
    ),
    'shop_seofilter_storefront_fields' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'shop_seofilter_storefront_fields_values' => array(
        'storefront' => array('varchar', 255, 'null' => 0),
        'field_id' => array('int', 11, 'null' => 0),
        'value' => array('text', 'null' => 0),
        'context' => array('enum', "'DEFAULT','PAGINATION'", 'null' => 0, 'default' => 'DEFAULT'),
        ':keys' => array(
            'PRIMARY' => array('storefront', 'field_id', 'context'),
        ),
    ),
);
